# Generated by Django 4.2.4 on 2023-12-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelType', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
