# Generated by Django 5.0 on 2023-12-12 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelType', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='lesson_thumbnails/')),
                ('file', models.FileField(upload_to='lesson_files/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'mp3', 'mp4'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelType.course')),
            ],
        ),
    ]
